# Generated by Django 3.2.12 on 2022-06-22 07:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='issued_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='register',
            name='no_of_days',
            field=models.IntegerField(default=0),
        ),
    ]
