# Generated by Django 3.2.12 on 2022-06-22 07:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220622_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='issued_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
